spring:
  application:
    name: user-manager
  datasource:
    url: "${DATABASE_URL:jdbc:postgresql://localhost:5432/users_db}"
    username: "${DATABASE_USERNAME:postgres}"
    password: "${DATABASE_PASSWORD:password}"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: true

app:
  validation:
    minimalAge: 18

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    url: /swagger/openapi.yml
